version: '3'
services:
  db_postgres:
  #restart: always
    container_name: db_postgres
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - volume_spring:/data
    ports:
      - "5434:5432"
    networks:
      - rede_spring
  backend-spring:
    depends_on:
      - db_postgres
    restart: always
    container_name: app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    build: .
    ports:
      - "9000:9000"
    networks:
      - rede_spring


volumes:
  volume_spring:

networks:
  rede_spring: