version: '3'
services:
  backend-spring:
    restart: always
    container_name: spring-docker
    build: .
    ports:
      - "9000:9000"
    networks:
      - rede_spring


volumes:
  volume_spring:

networks:
  rede_spring: